### PR TITLE
Allow linking and unlinking issues

### PR DESCRIPTION
**Pull request by tonyo**
Add necessary forms/methods to support linking and unlinking existing Redmine issues.
`sentry-github` (https://github.com/getsentry/sentry-github) was used as a reference.

---

This change is [Reviewable](https://reviewable.io/reviews/getsentry/sentry-redmine/6)

### CODE REVIEW

**Comment by tonyo** [comment]
Would be great to get some feedback on this. And if everything is OK, looks like it makes sense to release a new version of the plugin. Thanks!

**Comment by dcramer** [comment]
Somehow we missed this, but I'm inclined to not make any changes to the Redmine plugin ATM.

We're currently moving GitHub (and then Atlassian tools) to a new architecture which turns plugins into API providers + React components. It's part of our strategy of both expanding on the features plugins provide, but also moving away from the server-side rendering.

This is a WIP, but it should give you an idea of what I mean:

https://github.com/getsentry/sentry-github/pull/37

**Comment by tonyo** [comment]
@dcramer Returning to this PR, does it make sense now to move this plugin to a "new architecture" you've mentioned? I'm interested in working on it, I just want to make sure that it's the right moment and the architecture won't be changed again.
I've also noticed that the `sentry-github` plugin was moved to the `sentry-plugins` repo. Will the same happen to this plugin at some point?

**Comment by dcramer** [comment]
@rev112 yeah so everything thats on the new infrastructure under getsentry/ is being moved into sentry-plugins. There's no timeline on that, and its really whenever people feel like it at the moment. The new stuff has a lot of nice advantages, primarily that its much easier to deal with config and requests. I'd say if we want to add this, it'd make a lot of sense to do the same for Redmine at this point.

Of note we _are_ still evolving the new APIs, specifically right now to get Jira onto the new architecture. That probably doesn't block Redmine, and once it's in sentry-plugins its much easier for us to maintain compatibility if we make breaking changes.

**Comment by tonyo** [comment]
This is something from the past life.

**Pull request closed without merging**
